apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: rng
build:
  artifacts:
  - image: danielderepentigny/rng-svc
    context: rng-svc
    docker:
      dockerfile: Dockerfile
  - image: danielderepentigny/webapp
    context: webapp
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kube/rng-svc-deploy.yml
    - kube/rng-svc-svc.yml
    - kube/webapp-deploy.yml
    - kube/webapp-svc.yml
