apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rng-svc
  name: rng-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: rng-svc
  type: ClusterIP
status:
  loadBalancer: {}
