apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rng-svc
  name: rng-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng-svc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rng-svc
    spec:
      containers:
      - image: danielderepentigny/rng-svc:latest
        name: rng-svc
        resources: {}
status: {}
