apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rng-webapp
  name: rng-webapp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: rng-webapp
  type: LoadBalancer
status:
  loadBalancer: {}
